cal Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/Robojini/Tuturial_UI_Library/main/UI_Template_1"))()
local Window = Library.CreateLib("Acezosing", "RJTheme3")
local Tab = Window:NewTab("Trident")
local Section = Tab:NewSection("TRIDENT")
Section:NewButton("trident", "the script for trident survival v5", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/SWIMHUBISWIMMING/swimhub/refs/heads/main/free_trident.lua"))()
end)
local Tab = Window:NewTab("ESP")
local Section = Tab:NewSection("ESP")
Section:NewButton("ESP", "allows you to view through walls", function()
     loadstring(game:HttpGet("https://raw.githubusercontent.com/sashanz/-/refs/heads/main/вфцвфц.lua"))()
end)
local Tab = Window:NewTab("SILENT")
local Section = Tab:NewSection("SILENT")
Section:NewButton("SILENT AIM", "Bullets will often fly to the head", function()
     loadstring(game:HttpGet("https://raw.githubusercontent.com/sashanz/DWDA/refs/heads/main/DAW.LUA"))()
end)
local Tab = Window:NewTab("aimbot")
local Section = Tab:NewSection("AIMBOT")
Section:NewButton("AIMBOT", "auto aiming", function()
     loadstring(game:HttpGet("https://raw.githubusercontent.com/sashanz/-/refs/heads/main/redme.lua"))()
end)
local Tab = Window:NewTab("Noclip")
local Section = Tab:NewSection("SNoclip")
Section:NewButton("Noclip", "allows you to pass through walls", function()
     loadstring(game:HttpGet("https://raw.githubusercontent.com/sashanz/dwadawaw/refs/heads/main/noclip.lua"))()
end)
local Tab = Window:NewTab("SpeedHak")
local Section = Tab:NewSection("SpeedHak")
Section:NewButton("SpeedHak", "adjusts the speed", function()
     loadstring(game:HttpGet("https://raw.githubusercontent.com/sashanz/spedhack/refs/heads/main/sped%20hack.LUA"))()
end)
